name: build

on:
  push:
    branches:
      - master
      - 'renovate/**'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile --link-duplicates

      - run: yarn lint

      - name: glith deploy
        if: ${{ github.ref == 'refs/heads/master'}}
        run: |
          if [[ ! -z "$GLITCH_PROJECT_ID" ]] && [[ ! -z "$GLITCH_TOKEN" ]]
          then
            yarn sync-glitch
          else
            echo 'missing secrets'
          fi
        env:
          GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
          GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
          GH_REPO: ${{ github.repository }}
